# exported from PySB model 'MARM1'

from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, EnergyPattern, ANY, WILD
from sympy import exp, log

Model()

Monomer('RAFi', ['raf'])
Monomer('MEKi', ['mek'])
Monomer('EGF', ['rtk'])
Monomer('EGFR', ['SH2', 'rtk', 'rtkf'])
Monomer('GRB2', ['SH2', 'SH3'])
Monomer('SOS1', ['S1134', 'SH3', 'ras'], {'S1134': ['p', 'u']})
Monomer('RAS', ['raf', 'sos1', 'state'], {'state': ['gdp', 'gtp']})
Monomer('BRAF', ['AA600', 'RBD', 'mek', 'raf', 'rafi'], {'AA600': ['E']})
Monomer('CRAF', ['RBD', 'mek', 'raf', 'rafi'])
Monomer('MEK', ['Dsite', 'meki', 'phospho', 'raf'], {'phospho': ['p', 'u']})
Monomer('ERK', ['CD', 'phospho'], {'phospho': ['p', 'u']})
Monomer('DUSP', ['erk'])
Monomer('SPRY', ['SH3'])

Parameter('RAFi_0', 0.0)
Parameter('MEKi_0', 0.0)
Parameter('EGF_0', 0.0)
Parameter('bind_EGF_EGFR_kf', 10.0)
Parameter('bind_EGF_EGFR_kD', 0.01)
Parameter('bind_EGF_EGFR_phi', 1.0)
Parameter('bind_EGFR_EGFR_kf', 10.0)
Parameter('bind_EGFR_EGFR_kD', 100.0)
Parameter('bind_EGFR_EGFR_phi', 1.0)
Parameter('ep_EGFR_EGFR_mod_EGF_single_deltaG', 0.001)
Parameter('ep_EGFR_EGFR_mod_EGF_double_deltaG', 0.001)
Parameter('bind_RTK_GRB2_kf', 10.0)
Parameter('bind_RTK_GRB2_kD', 0.01)
Parameter('EGFR_eq', 10000.0)
Parameter('synthesize_ERKphosphop_EGFR_kdeg', 10.0)
Parameter('EGFR_crispr', 1.0)
Parameter('catalyze_GRB2_RTKSH2ANY_deg_kcat', 10.0)
Parameter('bind_GRB2_SOS1_kf', 10.0)
Parameter('bind_GRB2_SOS1_kD', 0.01)
Parameter('bind_SOS1_RAS_kf', 10.0)
Parameter('bind_SOS1_RAS_kD', 0.01)
Parameter('catalyze_SOS1_RAS_gtp_kcat', 0.01)
Parameter('catalyze_NF1_RAS_gdp_kcatr', 100.0)
Parameter('bind_RAF_RAF_kf', 10.0)
Parameter('bind_RAF_RAF_kD', 0.01)
Parameter('bind_RAF_RAF_phi', 1.0)
Parameter('bind_RASstategtp_RAF_kf', 10.0)
Parameter('bind_RASstategtp_RAF_kD', 0.01)
Parameter('bind_RASstategtp_RAF_phi', 1.0)
Parameter('ep_RAF_RAF_mod_RASstategtp_double_deltaG', 1000.0)
Parameter('bind_RAFi_RAF_kf', 10.0)
Parameter('bind_RAFi_RAF_kD', 0.01)
Parameter('bind_RAFi_RAF_phi', 1.0)
Parameter('ep_RAF_RAF_mod_RAFi_single_deltaG', 0.001)
Parameter('ep_RAF_RAF_mod_RAFi_double_deltaG', 1000.0)
Parameter('bind_RAF_MEKphosphou_kf', 10.0)
Parameter('bind_RAF_MEKphosphou_kD', 0.01)
Parameter('bind_RAF_MEKphosphou_phi', 1.0)
Parameter('catalyze_RAFrafiNone_MEK_p_kcat', 10.0)
Parameter('catalyze_PP2A_MEK_u_kcatr', 1.0)
Parameter('bind_MEKi_MEK_kf', 10.0)
Parameter('bind_MEKi_MEK_kD', 0.01)
Parameter('bind_MEKi_MEK_phi', 1.0)
Parameter('ep_MEKphosphop_MEKi_deltaG', 100.0)
Parameter('bind_MEK_ERKphosphou_kf', 10.0)
Parameter('bind_MEK_ERKphosphou_kD', 0.01)
Parameter('catalyze_MEKmekiNone_phosphop_ERK_p_kcat', 10.0)
Parameter('SPRY_eq', 10000.0)
Parameter('synthesize_ERKphosphop_SPRY_kdeg', 10.0)
Parameter('synthesize_ERKphosphop_SPRY_ERK_gexpslope', 1000.0)
Parameter('bind_SPRY_GRB2_kf', 10.0)
Parameter('bind_SPRY_GRB2_kD', 0.01)
Parameter('catalyze_ERKphosphop_SOS1_pS1134_kbase', 0.0)
Parameter('catalyze_ERKphosphop_SOS1_pS1134_kcat', 10.0)
Parameter('catalyze_phosphatase_SOS1_uS1134_kcatr', 1.0)
Parameter('ep_SOS1S1134p_GRB2_deltaG', 2.0)
Parameter('synthesize_ERKphosphop_EGFR_ERK_gexpslope', 1000.0)
Parameter('DUSP_eq', 10000.0)
Parameter('synthesize_ERKphosphop_DUSP_ERK_gexpslope', 1000.0)
Parameter('synthesize_ERKphosphop_DUSP_kdeg', 10.0)
Parameter('bind_DUSP_ERKphosphop_kf', 10.0)
Parameter('bind_DUSP_ERKphosphop_kD', 0.01)
Parameter('catalyze_DUSP_ERK_u_kcatr', 1.0)
Parameter('BRAF_0', 0.0)
Parameter('CRAF_0', 0.0)
Parameter('RAS_0', 0.0)
Parameter('MEK_0', 0.0)
Parameter('ERK_0', 0.0)
Parameter('GRB2_0', 0.0)
Parameter('SOS1_0', 0.0)
Parameter('pMEK_IF_scale', 1.0)
Parameter('pMEK_IF_offset', 0.1)
Parameter('pERK_IF_scale', 1.0)
Parameter('pERK_IF_offset', 0.1)

Expression('N_Avogadro', 6.02214085700000e+23)
Expression('volume', 1.00000000000000e-12)
Expression('m_Da_EGF', 6200.00000000000)
Expression('initRAFi', RAFi_0)
Expression('initMEKi', MEKi_0)
Expression('initEGF', 6.02214085854916e+23*EGF_0*(m_Da_EGF*N_Avogadro)**(-1))
Expression('bind_EGF_EGFR_kr', bind_EGF_EGFR_kf*bind_EGF_EGFR_kD)
Expression('Gf_bind_EGF_EGFR', log(bind_EGF_EGFR_kD))
Expression('Ea0_bind_EGF_EGFR', -(bind_EGF_EGFR_phi*log(bind_EGF_EGFR_kD) + log(bind_EGF_EGFR_kf)))
Expression('bind_EGFR_EGFR_kr', bind_EGFR_EGFR_kf*bind_EGFR_EGFR_kD)
Expression('Gf_bind_EGFR_EGFR', log(bind_EGFR_EGFR_kD))
Expression('Ea0_bind_EGFR_EGFR', -(bind_EGFR_EGFR_phi*log(bind_EGFR_EGFR_kD) + log(bind_EGFR_EGFR_kf)))
Expression('ep_EGFR_EGFR_mod_EGF_single_Gf', log(ep_EGFR_EGFR_mod_EGF_single_deltaG))
Expression('ep_EGFR_EGFR_mod_EGF_double_Gf', log(ep_EGFR_EGFR_mod_EGF_double_deltaG) + log(ep_EGFR_EGFR_mod_EGF_single_deltaG))
Expression('bind_RTK_GRB2_kr', bind_RTK_GRB2_kf*bind_RTK_GRB2_kD)
Expression('synthesize_ERKphosphop_EGFR_ksyn', 1000000.0*EGFR_eq*(N_Avogadro*volume)**(-1)*synthesize_ERKphosphop_EGFR_kdeg*EGFR_crispr)
Expression('bind_GRB2_SOS1_kr', bind_GRB2_SOS1_kf*bind_GRB2_SOS1_kD)
Expression('bind_SOS1_RAS_kr', bind_SOS1_RAS_kf*bind_SOS1_RAS_kD)
Expression('catalyze_NF1_RAS_gdp_kcat', catalyze_SOS1_RAS_gtp_kcat*catalyze_NF1_RAS_gdp_kcatr)
Expression('bind_BRAF_BRAF_kr', bind_RAF_RAF_kf*bind_RAF_RAF_kD)
Expression('Gf_bind_BRAF_BRAF', log(bind_RAF_RAF_kD))
Expression('Ea0_bind_BRAF_BRAF', -(bind_RAF_RAF_phi*log(bind_RAF_RAF_kD) + log(bind_RAF_RAF_kf)))
Expression('bind_BRAF_CRAF_kr', bind_RAF_RAF_kf*bind_RAF_RAF_kD)
Expression('Gf_bind_BRAF_CRAF', log(bind_RAF_RAF_kD))
Expression('Ea0_bind_BRAF_CRAF', -(bind_RAF_RAF_phi*log(bind_RAF_RAF_kD) + log(bind_RAF_RAF_kf)))
Expression('bind_CRAF_CRAF_kr', bind_RAF_RAF_kf*bind_RAF_RAF_kD)
Expression('Gf_bind_CRAF_CRAF', log(bind_RAF_RAF_kD))
Expression('Ea0_bind_CRAF_CRAF', -(bind_RAF_RAF_phi*log(bind_RAF_RAF_kD) + log(bind_RAF_RAF_kf)))
Expression('bind_RASstategtp_BRAF_kr', bind_RASstategtp_RAF_kf*bind_RASstategtp_RAF_kD)
Expression('Gf_bind_RASstategtp_BRAF', log(bind_RASstategtp_RAF_kD))
Expression('Ea0_bind_RASstategtp_BRAF', -(bind_RASstategtp_RAF_phi*log(bind_RASstategtp_RAF_kD) + log(bind_RASstategtp_RAF_kf)))
Expression('bind_RASstategtp_CRAF_kr', bind_RASstategtp_RAF_kf*bind_RASstategtp_RAF_kD)
Expression('Gf_bind_RASstategtp_CRAF', log(bind_RASstategtp_RAF_kD))
Expression('Ea0_bind_RASstategtp_CRAF', -(bind_RASstategtp_RAF_phi*log(bind_RASstategtp_RAF_kD) + log(bind_RASstategtp_RAF_kf)))
Expression('ep_RAF_RAF_mod_RASstategtp_double_Gf', log(ep_RAF_RAF_mod_RASstategtp_double_deltaG))
Expression('bind_BRAFi_RAF_kr', bind_RAFi_RAF_kf*bind_RAFi_RAF_kD)
Expression('Gf_bind_BRAFi_RAF', log(bind_RAFi_RAF_kD))
Expression('Ea0_bind_BRAFi_RAF', -(bind_RAFi_RAF_phi*log(bind_RAFi_RAF_kD) + log(bind_RAFi_RAF_kf)))
Expression('bind_CRAFi_RAF_kr', bind_RAFi_RAF_kf*bind_RAFi_RAF_kD)
Expression('Gf_bind_CRAFi_RAF', log(bind_RAFi_RAF_kD))
Expression('Ea0_bind_CRAFi_RAF', -(bind_RAFi_RAF_phi*log(bind_RAFi_RAF_kD) + log(bind_RAFi_RAF_kf)))
Expression('ep_RAF_RAF_mod_RAFi_single_Gf', log(ep_RAF_RAF_mod_RAFi_single_deltaG))
Expression('ep_RAF_RAF_mod_RAFi_double_Gf', log(ep_RAF_RAF_mod_RAFi_double_deltaG) + log(ep_RAF_RAF_mod_RAFi_single_deltaG))
Expression('bind_BRAF_MEKphosphou_kr', bind_RAF_MEKphosphou_kf*bind_RAF_MEKphosphou_kD)
Expression('Gf_bind_BRAF_MEKphosphou', log(bind_RAF_MEKphosphou_kD))
Expression('Ea0_bind_BRAF_MEKphosphou', -(bind_RAF_MEKphosphou_phi*log(bind_RAF_MEKphosphou_kD) + log(bind_RAF_MEKphosphou_kf)))
Expression('bind_CRAF_MEKphosphou_kr', bind_RAF_MEKphosphou_kf*bind_RAF_MEKphosphou_kD)
Expression('Gf_bind_CRAF_MEKphosphou', log(bind_RAF_MEKphosphou_kD))
Expression('Ea0_bind_CRAF_MEKphosphou', -(bind_RAF_MEKphosphou_phi*log(bind_RAF_MEKphosphou_kD) + log(bind_RAF_MEKphosphou_kf)))
Expression('catalyze_PP2A_MEK_u_kcat', catalyze_RAFrafiNone_MEK_p_kcat*catalyze_PP2A_MEK_u_kcatr)
Expression('bind_MEKi_MEK_kr', bind_MEKi_MEK_kf*bind_MEKi_MEK_kD)
Expression('Gf_bind_MEKi_MEK', log(bind_MEKi_MEK_kD))
Expression('Ea0_bind_MEKi_MEK', -(bind_MEKi_MEK_phi*log(bind_MEKi_MEK_kD) + log(bind_MEKi_MEK_kf)))
Expression('ep_MEKphosphop_MEKi_Gf', log(ep_MEKphosphop_MEKi_deltaG))
Expression('bind_MEK_ERKphosphou_kr', bind_MEK_ERKphosphou_kf*bind_MEK_ERKphosphou_kD)
Expression('synthesize_ERKphosphop_SPRY_ksyn', 1000000.0*SPRY_eq*(N_Avogadro*volume)**(-1)*synthesize_ERKphosphop_SPRY_kdeg)
Expression('synthesize_ERKphosphop_SPRY_kmodslope', synthesize_ERKphosphop_SPRY_ERK_gexpslope*synthesize_ERKphosphop_SPRY_kdeg)
Expression('bind_SPRY_GRB2_kr', bind_SPRY_GRB2_kf*bind_SPRY_GRB2_kD)
Expression('catalyze_phosphatase_SOS1_uS1134_kcat', catalyze_ERKphosphop_SOS1_pS1134_kcat*catalyze_phosphatase_SOS1_uS1134_kcatr)
Expression('__reverse_bind_GRB2_SOS1_local1', bind_GRB2_SOS1_kD*bind_GRB2_SOS1_kf*ep_SOS1S1134p_GRB2_deltaG)
Expression('synthesize_ERKphosphop_EGFR_kmodslope', synthesize_ERKphosphop_EGFR_ERK_gexpslope*synthesize_ERKphosphop_EGFR_kdeg)
Expression('synthesize_ERKphosphop_DUSP_ksyn', 1000000.0*DUSP_eq*(N_Avogadro*volume)**(-1)*synthesize_ERKphosphop_DUSP_kdeg)
Expression('synthesize_ERKphosphop_DUSP_kmodslope', synthesize_ERKphosphop_DUSP_ERK_gexpslope*synthesize_ERKphosphop_DUSP_kdeg)
Expression('bind_DUSP_ERKphosphop_kr', bind_DUSP_ERKphosphop_kf*bind_DUSP_ERKphosphop_kD)
Expression('catalyze_DUSP_ERK_u_kcat', catalyze_MEKmekiNone_phosphop_ERK_p_kcat*catalyze_DUSP_ERK_u_kcatr)
Expression('initBRAF', 1000000.0*BRAF_0*(N_Avogadro*volume)**(-1))
Expression('initCRAF', 1000000.0*CRAF_0*(N_Avogadro*volume)**(-1))
Expression('initRAS', 1000000.0*RAS_0*(N_Avogadro*volume)**(-1))
Expression('initMEK', 1000000.0*MEK_0*(N_Avogadro*volume)**(-1))
Expression('initERK', 1000000.0*ERK_0*(N_Avogadro*volume)**(-1))
Expression('initGRB2', 1000000.0*GRB2_0*(N_Avogadro*volume)**(-1))
Expression('initSOS1', 1000000.0*SOS1_0*(N_Avogadro*volume)**(-1))

Observable('tBRAF', BRAF())
Observable('tBRAF600E', BRAF(AA600='E'))
Observable('tCRAF', CRAF())
Observable('tRAS', RAS())
Observable('tRAFi', RAFi())
Observable('tMEK', MEK())
Observable('tMEKi', MEKi())
Observable('tERK', ERK())
Observable('tDUSP', DUSP())
Observable('tEGFR', EGFR())
Observable('tEGF', EGF())
Observable('tGRB2', GRB2())
Observable('tSPRY', SPRY())
Observable('tSOS1', SOS1())
Observable('pERK', ERK(phospho='p'))
Observable('pS1134SOS1', SOS1(S1134='p'))
Observable('pMEK', MEK(phospho='p'))
Observable('SOS1_active', GRB2(SH2=ANY, SH3=1) % SOS1(SH3=1))
Observable('uS1134SOS1', SOS1(S1134='u'))
Observable('RAS_gtp', RAS(state='gtp'))
Observable('RAS_gdp', RAS(state='gdp'))
Observable('active_RAF_dimers', BRAF(RBD=ANY, raf=1, rafi=None) % BRAF(RBD=ANY, raf=1) + BRAF(RBD=ANY, raf=1, rafi=None) % CRAF(RBD=ANY, raf=1) + CRAF(RBD=ANY, raf=1, rafi=None) % BRAF(RBD=ANY, raf=1) + CRAF(RBD=ANY, raf=1, rafi=None) % CRAF(RBD=ANY, raf=1))
Observable('active_RAF_monomers', BRAF(AA600='E', raf=None, rafi=None))
Observable('active_MEK', MEK(meki=None, phospho='p'))
Observable('uMEK', MEK(phospho='u'))
Observable('uERK', ERK(phospho='u'))

Expression('tBRAF_obs', 1.0e-6*tBRAF*N_Avogadro*volume)
Expression('tCRAF_obs', 1.0e-6*tCRAF*N_Avogadro*volume)
Expression('tRAS_obs', 1.0e-6*tRAS*N_Avogadro*volume)
Expression('tMEK_obs', 1.0e-6*tMEK*N_Avogadro*volume)
Expression('tDUSP_obs', 1.0e-6*tDUSP*N_Avogadro*volume)
Expression('tEGFR_obs', 1.0e-6*tEGFR*N_Avogadro*volume)
Expression('tEGF_obs', 1.0e-6*tEGF*N_Avogadro*volume)
Expression('tGRB2_obs', 1.0e-6*tGRB2*N_Avogadro*volume)
Expression('tSPRY_obs', 1.0e-6*tSPRY*N_Avogadro*volume)
Expression('tSOS1_obs', 1.0e-6*tSOS1*N_Avogadro*volume)
Expression('tERK_obs', 1.0e-6*tERK*N_Avogadro*volume)
Expression('pERK_obs', pERK*tERK**(-1))
Expression('pS1134SOS1_obs', pS1134SOS1*tSOS1**(-1))
Expression('pMEK_obs', pMEK*tMEK**(-1))
Expression('pERK_IF_obs', pERK_IF_offset + pERK_IF_scale*pERK_obs)
Expression('pMEK_IF_obs', pMEK_IF_offset + pMEK_IF_scale*pMEK_obs)

Rule('EGF_and_EGFR_bind_and_dissociate', EGF(rtk=None) + EGFR(rtkf=None) | EGF(rtk=1) % EGFR(rtkf=1), bind_EGF_EGFR_phi, Ea0_bind_EGF_EGFR, energy=True)
Rule('EGFR_and_EGFR_bind_and_dissociate', EGFR(rtk=None) + EGFR(rtk=None) | EGFR(rtk=1) % EGFR(rtk=1), bind_EGFR_EGFR_phi, Ea0_bind_EGFR_EGFR, energy=True)
Rule('transactivated_RTK_dimers_bind_GRB2', EGFR(rtk=1, rtkf=ANY) % EGFR(SH2=None, rtk=1) + GRB2(SH2=None) >> EGFR(rtk=1, rtkf=ANY) % EGFR(SH2=2, rtk=1) % GRB2(SH2=2), bind_RTK_GRB2_kf)
Rule('GRB2_dissociates_from_RTK', EGFR(SH2=1) % GRB2(SH2=1) >> EGFR(SH2=None) + GRB2(SH2=None), bind_RTK_GRB2_kr)
Rule('basal_synthesis_EGFR', None >> EGFR(SH2=None, rtk=None, rtkf=None), synthesize_ERKphosphop_EGFR_ksyn)
Rule('basal_degradation_EGFR', EGFR() >> None, synthesize_ERKphosphop_EGFR_kdeg, delete_molecules=True)
Rule('GRB2_degrades_activeRTK_dimers', EGFR(SH2=ANY, rtk=1) % EGFR(SH2=None, rtk=1) >> None, catalyze_GRB2_RTKSH2ANY_deg_kcat, delete_molecules=True)
Rule('GRB2_degrades_doubleactiveRTK_dimers', EGFR(SH2=ANY, rtk=1) % EGFR(SH2=ANY, rtk=1) >> None, catalyze_GRB2_RTKSH2ANY_deg_kcat, delete_molecules=True)
Rule('GRB2_degrades_activeRTK_monomers', EGFR(SH2=ANY, rtk=None) >> None, catalyze_GRB2_RTKSH2ANY_deg_kcat, delete_molecules=True)
Rule('GRB2_binds_SOS1', GRB2(SH3=None) + SOS1(SH3=None) >> GRB2(SH3=1) % SOS1(SH3=1), bind_GRB2_SOS1_kf)
Rule('GRB2_dissociates_from_SOS1', GRB2(SH3=1) % SOS1(SH3=1) >> GRB2(SH3=None) + SOS1(SH3=None), bind_GRB2_SOS1_kr)
Rule('RTK_and_GRB2_bound_SOS1_binds_RASgdp', GRB2(SH2=ANY, SH3=1) % SOS1(SH3=1, ras=None) + RAS(sos1=None, state='gdp') >> GRB2(SH2=ANY, SH3=1) % SOS1(SH3=1, ras=2) % RAS(sos1=2, state='gdp'), bind_SOS1_RAS_kf)
Rule('SOS1_dissociates_from_RAS', SOS1(ras=1) % RAS(sos1=1) >> SOS1(ras=None) + RAS(sos1=None), bind_SOS1_RAS_kr)
Rule('SOS1_catalyzes_RAS_guanosine_exchange', SOS1(ras=1) % RAS(sos1=1, state='gdp') >> SOS1(ras=None) + RAS(sos1=None, state='gtp'), catalyze_SOS1_RAS_gtp_kcat)
Rule('RAS_hydrolisis_GTP', RAS(raf=None, state='gtp') >> RAS(raf=None, state='gdp'), catalyze_NF1_RAS_gdp_kcat)
Rule('BRAF_and_BRAF_bind_and_dissociate', BRAF(raf=None) + BRAF(raf=None) | BRAF(raf=1) % BRAF(raf=1), bind_RAF_RAF_phi, Ea0_bind_BRAF_BRAF, energy=True)
Rule('BRAF_and_CRAF_bind_and_dissociate', BRAF(raf=None) + CRAF(raf=None) | BRAF(raf=1) % CRAF(raf=1), bind_RAF_RAF_phi, Ea0_bind_BRAF_CRAF, energy=True)
Rule('CRAF_and_CRAF_bind_and_dissociate', CRAF(raf=None) + CRAF(raf=None) | CRAF(raf=1) % CRAF(raf=1), bind_RAF_RAF_phi, Ea0_bind_CRAF_CRAF, energy=True)
Rule('RASgtp_and_BRAF_bind_and_dissociate', RAS(raf=None, state='gtp') + BRAF(RBD=None) | RAS(raf=1, state='gtp') % BRAF(RBD=1), bind_RASstategtp_RAF_phi, Ea0_bind_RASstategtp_BRAF, energy=True)
Rule('RASgtp_and_CRAF_bind_and_dissociate', RAS(raf=None, state='gtp') + CRAF(RBD=None) | RAS(raf=1, state='gtp') % CRAF(RBD=1), bind_RASstategtp_RAF_phi, Ea0_bind_RASstategtp_CRAF, energy=True)
Rule('GTP_hydrolysis_dissociates_BRAF_from_RAS', RAS(raf=1, state='gtp') % BRAF(RBD=1) >> RAS(raf=None, state='gdp') + BRAF(RBD=None), catalyze_NF1_RAS_gdp_kcat)
Rule('GTP_hydrolysis_dissociates_CRAF_from_RAS', RAS(raf=1, state='gtp') % CRAF(RBD=1) >> RAS(raf=None, state='gdp') + CRAF(RBD=None), catalyze_NF1_RAS_gdp_kcat)
Rule('RAFi_and_BRAF_bind_and_dissociate', RAFi(raf=None) + BRAF(rafi=None) | RAFi(raf=1) % BRAF(rafi=1), bind_RAFi_RAF_phi, Ea0_bind_BRAFi_RAF, energy=True)
Rule('RAFi_and_CRAF_bind_and_dissociate', RAFi(raf=None) + CRAF(rafi=None) | RAFi(raf=1) % CRAF(rafi=1), bind_RAFi_RAF_phi, Ea0_bind_CRAFi_RAF, energy=True)
Rule('BRAF_and_uMEK_bind_and_dissociate', BRAF(mek=None) + MEK(phospho='u', raf=None) | BRAF(mek=1) % MEK(phospho='u', raf=1), bind_RAF_MEKphosphou_phi, Ea0_bind_BRAF_MEKphosphou, energy=True)
Rule('CRAF_and_uMEK_bind_and_dissociate', CRAF(mek=None) + MEK(phospho='u', raf=None) | CRAF(mek=1) % MEK(phospho='u', raf=1), bind_RAF_MEKphosphou_phi, Ea0_bind_CRAF_MEKphosphou, energy=True)
Rule('BRAF_BRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % BRAF(RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + BRAF(RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('BRAF_CRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % BRAF(RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + BRAF(RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('CRAF_BRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % CRAF(RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + CRAF(RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('CRAF_CRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % CRAF(RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + CRAF(RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_1', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', mek=1, raf=None, rafi=None) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', mek=None, raf=None, rafi=None), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_2', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', RBD=None, mek=1, raf=ANY, rafi=None) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', RBD=None, mek=None, raf=ANY, rafi=None), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_3', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=None, raf=2) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=None, raf=2), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_4', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=None, raf=2) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=None, raf=2), catalyze_RAFrafiNone_MEK_p_kcat)
Rule('MEK_is_dephosphorylated', MEK(phospho='p') >> MEK(phospho='u'), catalyze_PP2A_MEK_u_kcat)
Rule('MEKi_and_MEK_bind_and_dissociate', MEKi(mek=None) + MEK(meki=None) | MEKi(mek=1) % MEK(meki=1), bind_MEKi_MEK_phi, Ea0_bind_MEKi_MEK, energy=True)
Rule('MEK_binds_uERK', MEK(Dsite=None) + ERK(CD=None, phospho='u') >> MEK(Dsite=1) % ERK(CD=1, phospho='u'), bind_MEK_ERKphosphou_kf)
Rule('MEK_dissociates_from_ERK', MEK(Dsite=1) % ERK(CD=1) >> MEK(Dsite=None) + ERK(CD=None), bind_MEK_ERKphosphou_kr)
Rule('pMEK_phosphorylates_ERK', ERK(CD=1, phospho='u') % MEK(Dsite=1, meki=None, phospho='p') >> ERK(CD=None, phospho='p') + MEK(Dsite=None, meki=None, phospho='p'), catalyze_MEKmekiNone_phosphop_ERK_p_kcat)
Rule('basal_synthesis_SPRY', None >> SPRY(SH3=None), synthesize_ERKphosphop_SPRY_ksyn)
Rule('basal_degradation_SPRY', SPRY() >> None, synthesize_ERKphosphop_SPRY_kdeg, delete_molecules=True)
Rule('ERK_synthesizes_SPRY', None + ERK(phospho='p') >> SPRY(SH3=None) + ERK(phospho='p'), synthesize_ERKphosphop_SPRY_kmodslope)
Rule('SPRY_binds_GRB2', SPRY(SH3=None) + GRB2(SH3=None) >> SPRY(SH3=1) % GRB2(SH3=1), bind_SPRY_GRB2_kf)
Rule('SPRY_dissociates_from_GRB2', SPRY(SH3=1) % GRB2(SH3=1) >> SPRY(SH3=None) + GRB2(SH3=None), bind_SPRY_GRB2_kr)
Rule('SOS1_is_phosphorylated', SOS1(S1134='u') >> SOS1(S1134='p'), catalyze_ERKphosphop_SOS1_pS1134_kbase)
Rule('SOS1_is_dephosphorylated', SOS1(S1134='p') >> SOS1(S1134='u'), catalyze_phosphatase_SOS1_uS1134_kcat)
Rule('pERK_phosphorylates_SOS1', ERK(phospho='p') + SOS1(S1134='u') >> ERK(phospho='p') + SOS1(S1134='p'), catalyze_ERKphosphop_SOS1_pS1134_kcat)
Rule('pSOS1_has_modulated_affinity_to_GRB2', SOS1(S1134='p', SH3=1) % GRB2(SH3=1) >> SOS1(S1134='p', SH3=None) + GRB2(SH3=None), __reverse_bind_GRB2_SOS1_local1)
Rule('ERK_synthesizes_EGFR', None + ERK(phospho='p') >> EGFR(SH2=None, rtk=None, rtkf=None) + ERK(phospho='p'), synthesize_ERKphosphop_EGFR_kmodslope)
Rule('basal_synthesis_DUSP', None >> DUSP(erk=None), synthesize_ERKphosphop_DUSP_ksyn)
Rule('basal_degradation_DUSP', DUSP() >> None, synthesize_ERKphosphop_DUSP_kdeg, delete_molecules=True)
Rule('ERK_synthesizes_DUSP', None + ERK(phospho='p') >> DUSP(erk=None) + ERK(phospho='p'), synthesize_ERKphosphop_DUSP_kmodslope)
Rule('DUSP_binds_pERK', DUSP(erk=None) + ERK(CD=None, phospho='p') >> DUSP(erk=1) % ERK(CD=1, phospho='p'), bind_DUSP_ERKphosphop_kf)
Rule('DUSP_dissociates_from_ERK', DUSP(erk=1) % ERK(CD=1) >> DUSP(erk=None) + ERK(CD=None), bind_DUSP_ERKphosphop_kr)
Rule('DUSP_dephosphorylates_ERK', ERK(CD=1, phospho='p') % DUSP(erk=1) >> ERK(CD=None, phospho='u') + DUSP(erk=None), catalyze_DUSP_ERK_u_kcat)

EnergyPattern('ep_bind_EGF_EGFR', EGF(rtk=1) % EGFR(rtkf=1), Gf_bind_EGF_EGFR)
EnergyPattern('ep_bind_EGFR_EGFR', EGFR(rtk=1) % EGFR(rtk=1), Gf_bind_EGFR_EGFR)
EnergyPattern('ep_EGFR_EGFR_mod_EGF_single', EGFR(rtk=1, rtkf=None) % EGFR(rtk=1, rtkf=2) % EGF(rtk=2), ep_EGFR_EGFR_mod_EGF_single_Gf)
EnergyPattern('ep_EGFR_EGFR_mod_EGF_double', EGF(rtk=2) % EGFR(rtk=1, rtkf=2) % EGFR(rtk=1, rtkf=3) % EGF(rtk=3), ep_EGFR_EGFR_mod_EGF_double_Gf)
EnergyPattern('ep_bind_BRAF_BRAF', BRAF(raf=1) % BRAF(raf=1), Gf_bind_BRAF_BRAF)
EnergyPattern('ep_bind_BRAF_CRAF', BRAF(raf=1) % CRAF(raf=1), Gf_bind_BRAF_CRAF)
EnergyPattern('ep_bind_CRAF_CRAF', CRAF(raf=1) % CRAF(raf=1), Gf_bind_CRAF_CRAF)
EnergyPattern('ep_bind_RASstategtp_BRAF', RAS(raf=1, state='gtp') % BRAF(RBD=1), Gf_bind_RASstategtp_BRAF)
EnergyPattern('ep_bind_RASstategtp_CRAF', RAS(raf=1, state='gtp') % CRAF(RBD=1), Gf_bind_RASstategtp_CRAF)
EnergyPattern('ep_BRAF_BRAF_mod_RAS_double', RAS(raf=2, state='gtp') % BRAF(RBD=2, raf=1) % BRAF(RBD=3, raf=1) % RAS(raf=3, state='gtp'), ep_RAF_RAF_mod_RASstategtp_double_Gf)
EnergyPattern('ep_BRAF_CRAF_mod_RAS_double', RAS(raf=2, state='gtp') % BRAF(RBD=2, raf=1) % CRAF(RBD=3, raf=1) % RAS(raf=3, state='gtp'), ep_RAF_RAF_mod_RASstategtp_double_Gf)
EnergyPattern('ep_CRAF_CRAF_mod_RAS_double', RAS(raf=2, state='gtp') % CRAF(RBD=2, raf=1) % CRAF(RBD=3, raf=1) % RAS(raf=3, state='gtp'), ep_RAF_RAF_mod_RASstategtp_double_Gf)
EnergyPattern('ep_bind_BRAFi_RAF', RAFi(raf=1) % BRAF(rafi=1), Gf_bind_BRAFi_RAF)
EnergyPattern('ep_bind_CRAFi_RAF', RAFi(raf=1) % CRAF(rafi=1), Gf_bind_CRAFi_RAF)
EnergyPattern('ep_BRAF_BRAF_mod_RAFi_single', BRAF(raf=1, rafi=None) % BRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_Gf)
EnergyPattern('ep_BRAF_CRAF_mod_RAFi_single', BRAF(raf=1, rafi=None) % CRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_Gf)
EnergyPattern('ep_CRAF_BRAF_mod_RAFi_single', CRAF(raf=1, rafi=None) % BRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_Gf)
EnergyPattern('ep_CRAF_CRAF_mod_RAFi_single', CRAF(raf=1, rafi=None) % CRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_Gf)
EnergyPattern('ep_BRAF_BRAF_mod_RAFi_double', RAFi(raf=2) % BRAF(raf=1, rafi=2) % BRAF(raf=1, rafi=3) % RAFi(raf=3), ep_RAF_RAF_mod_RAFi_double_Gf)
EnergyPattern('ep_BRAF_CRAF_mod_RAFi_double', RAFi(raf=2) % BRAF(raf=1, rafi=2) % CRAF(raf=1, rafi=3) % RAFi(raf=3), ep_RAF_RAF_mod_RAFi_double_Gf)
EnergyPattern('ep_CRAF_CRAF_mod_RAFi_double', RAFi(raf=2) % CRAF(raf=1, rafi=2) % CRAF(raf=1, rafi=3) % RAFi(raf=3), ep_RAF_RAF_mod_RAFi_double_Gf)
EnergyPattern('ep_bind_BRAF_MEKphosphou', BRAF(mek=1) % MEK(phospho='u', raf=1), Gf_bind_BRAF_MEKphosphou)
EnergyPattern('ep_bind_CRAF_MEKphosphou', CRAF(mek=1) % MEK(phospho='u', raf=1), Gf_bind_CRAF_MEKphosphou)
EnergyPattern('ep_bind_MEKi_MEK', MEKi(mek=1) % MEK(meki=1), Gf_bind_MEKi_MEK)
EnergyPattern('ep_MEKphosphop_MEKi_single', MEK(meki=1, phospho='p') % MEKi(mek=1), ep_MEKphosphop_MEKi_Gf)

Initial(RAFi(raf=None), initRAFi, fixed=True)
Initial(MEKi(mek=None), initMEKi, fixed=True)
Initial(EGF(rtk=None), initEGF, fixed=True)
Initial(BRAF(AA600='E', RBD=None, mek=None, raf=None, rafi=None), initBRAF)
Initial(CRAF(RBD=None, mek=None, raf=None, rafi=None), initCRAF)
Initial(RAS(raf=None, sos1=None, state='gdp'), initRAS)
Initial(MEK(Dsite=None, meki=None, phospho='u', raf=None), initMEK)
Initial(ERK(CD=None, phospho='u'), initERK)
Initial(GRB2(SH2=None, SH3=None), initGRB2)
Initial(SOS1(S1134='u', SH3=None, ras=None), initSOS1)

Annotation(RAFi, 'http://identifiers.org/chebi/63637', 'is')
Annotation(MEKi, 'http://identifiers.org/chebi/90851', 'is')
Annotation(EGF, 'http://identifiers.org/uniprot/P01133', 'is')
Annotation(EGFR, 'http://identifiers.org/uniprot/P00533', 'is')
Annotation(GRB2, 'http://identifiers.org/uniprot/P62993', 'is')
Annotation(SOS1, 'http://identifiers.org/uniprot/Q07889', 'is')
Annotation(RAS, 'http://identifiers.org/uniprot/P01111', 'is')
Annotation(RAS, 'http://identifiers.org/uniprot/P01116', 'is')
Annotation(RAS, 'http://identifiers.org/uniprot/P01112', 'is')
Annotation(EGF_and_EGFR_bind_and_dissociate, 'http://identifiers.org/pubmed/16946702', 'isDescribedBy')
Annotation(EGFR_and_EGFR_bind_and_dissociate, 'http://identifiers.org/pubmed/16946702', 'isDescribedBy')
Annotation(transactivated_RTK_dimers_bind_GRB2, 'http://identifiers.org/pubmed/16777603', 'isDescribedBy')
Annotation(GRB2_dissociates_from_SOS1, 'http://identifiers.org/pubmed/7893993', 'isDescribedBy')
Annotation(RTK_and_GRB2_bound_SOS1_binds_RASgdp, 'http://identifiers.org/pubmed/26565026', 'isDescribedBy')
Annotation(BRAF, 'http://identifiers.org/uniprot/P15056', 'is')
Annotation(CRAF, 'http://identifiers.org/uniprot/P04049', 'is')
Annotation(MEK, 'http://identifiers.org/uniprot/Q02750', 'is')
Annotation(MEK, 'http://identifiers.org/uniprot/P36507', 'is')
Annotation(ERK, 'http://identifiers.org/uniprot/P27361', 'is')
Annotation(ERK, 'http://identifiers.org/uniprot/P28482', 'is')
Annotation(RASgtp_and_BRAF_bind_and_dissociate, 'http://identifiers.org/pubmed/7969158', 'isDescribedBy')
Annotation(RASgtp_and_CRAF_bind_and_dissociate, 'http://identifiers.org/pubmed/7969158', 'isDescribedBy')
Annotation(BRAF_and_uMEK_bind_and_dissociate, 'http://identifiers.org/pubmed/25155755', 'isDescribedBy')
Annotation(CRAF_and_uMEK_bind_and_dissociate, 'http://identifiers.org/pubmed/25155755', 'isDescribedBy')
Annotation(MEK_dissociates_from_ERK, 'http://identifiers.org/pubmed/10567369', 'isDescribedBy')
Annotation(MEK_dissociates_from_ERK, 'http://identifiers.org/pubmed/10655591', 'isDescribedBy')
Annotation(MEK_dissociates_from_ERK, 'http://identifiers.org/pubmed/11157753', 'isDescribedBy')
Annotation(MEK_dissociates_from_ERK, 'http://identifiers.org/pubmed/15979847', 'isDescribedBy')
Annotation(pMEK_phosphorylates_ERK, 'http://identifiers.org/pubmed/19406201', 'isDescribedBy')
Annotation(DUSP, 'http://identifiers.org/uniprot/Q13115', 'is')
Annotation(DUSP, 'http://identifiers.org/uniprot/Q16828', 'is')
Annotation(SPRY, 'http://identifiers.org/uniprot/O43597', 'is')
Annotation(SPRY, 'http://identifiers.org/uniprot/Q9C004', 'is')
Annotation(DUSP_dissociates_from_ERK, 'http://identifiers.org/pubmed/10655591', 'isDescribedBy')
Annotation(DUSP_dissociates_from_ERK, 'http://identifiers.org/pubmed/11157753', 'isDescribedBy')

